name = "miaumiau"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "miaumiau-db"
database_id = "placeholder"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "miaumiau-media"
